variable "comment" {
  type        = "string"
  description = "(Optional) An optional comment about the public key."
  default     = ""
}


variable "public-key" {
  type = "string"
  default = ""
  description = " (Required) The encoded public key that you want to add to CloudFront to use with features like field-level encryption."
}

variable "name" {
  type = "string"
  default = ""
  description = "(Optional) The name for the public key. By default generated by Terraform"
}